version: "3"
services:
  
  ui:
    build:
      context: ./
      dockerfile: ./stays-ui/Dockerfile
    ports:
      - "3000:3000"

  platform:
    build:
      context: ./
      dockerfile: ./stays-platform/Dockerfile
    ports:
      - "3001:3001"
  
